// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1VXvb6_FKcNShc2T9arfeFzl285onxmY',
    appId: '1:839254064431:web:d32e72316d58dee8d4f5da',
    messagingSenderId: '839254064431',
    projectId: 'esp8266-7280d',
    authDomain: 'esp8266-7280d.firebaseapp.com',
    databaseURL: 'https://esp8266-7280d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp8266-7280d.firebasestorage.app',
    measurementId: 'G-RHXK80HYT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpoJHeDgyMd9TnXJkzOMu44jOIi4HDjEA',
    appId: '1:839254064431:android:75865897c44f77efd4f5da',
    messagingSenderId: '839254064431',
    projectId: 'esp8266-7280d',
    databaseURL: 'https://esp8266-7280d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp8266-7280d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEHjXSWp3qVvudoX4daFfFX2_EQxjAEKE',
    appId: '1:839254064431:ios:501506e320360be4d4f5da',
    messagingSenderId: '839254064431',
    projectId: 'esp8266-7280d',
    databaseURL: 'https://esp8266-7280d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp8266-7280d.firebasestorage.app',
    iosBundleId: 'com.example.bai1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1VXvb6_FKcNShc2T9arfeFzl285onxmY',
    appId: '1:839254064431:web:eeae46f67e963372d4f5da',
    messagingSenderId: '839254064431',
    projectId: 'esp8266-7280d',
    authDomain: 'esp8266-7280d.firebaseapp.com',
    databaseURL: 'https://esp8266-7280d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp8266-7280d.firebasestorage.app',
    measurementId: 'G-PQ12D37BWR',
  );
}
